### PR TITLE
revert FFmpeg to supported release, add AV1 decoding

### PR DESCRIPTION
**Pull request by wsnipex**
fixes: #126 #127

### CODE REVIEW

**Comment by Erick555** [comment]
@wsnipex dav1d is already in [runtime](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/21.08/elements/components/dav1d.bst) so you shouldn't need to bundle it (unless you try to force older version)

**Comment by wsnipex** [comment]
ok, didn't see that.
The more interesting question is why libheif started to fail now. It's totally unlreated

**Comment by Erick555** [comment]
It may be related as dav1d is one of dependencies of libheif and it may get confused when you added new dav1d static library to the mix. There are many weird  things happening there in general i.e. libde265 is dep of libheif but it's build after it so the latter won't find it during build.

**Comment by wsnipex** [comment]
> @wsnipex dav1d is already in [runtime](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/21.08/elements/components/dav1d.bst) so you shouldn't need to bundle it (unless you try to force older version). BTW: why `--default-library=static`? That would use more space.

I've removed the static build for dav1d, but I'll keep our version, since it's used on all other kodi platforms as well.

**Comment by Erick555** [comment]
I think with dav1d as shared library the https://github.com/flathub/tv.kodi.Kodi/commit/8e60a27f8a857c7ef54a4680b857a3a99282e542 may be not needed anymore.

**Comment by wsnipex** [comment]
maybe,  but we still want the same options as upstream

**Pull request merged**
