### PR TITLE
Add python 3 module

### PR DESCRIPTION
**Pull request by razzeee**

### CODE REVIEW

**Comment by Erick555** [comment]
Maybe try building python as last module in order to not confuse others during build.

**Comment by razzeee** [comment]
@flathubbot  build


@Erick555 the idea was to have this in the start, to see if this even builds, without wasting as much CI

**Comment by wsnipex** [comment]
we should bump to  3.9.13, which fixed the sub interpreter issues.

**Comment by razzeee** [comment]
Hrm, but according to this user, this will cause some addons to fail. https://github.com/flathub/tv.kodi.Kodi/issues/163

And it seems like we will ship 3.8.8 as long as kodi 19 exists

**Comment by wsnipex** [comment]
ah, not sure why I supposed this PR is against beta branch. I meant we should bump to 3.9.13 in beta, same as upstream.
This version specifically fixes the addon crashes. Not that the reporter uses python 3.10, which doesn't have a fix yet, although it's due soon.

**Comment by razzeee** [comment]
Agreed, I figured, we need to find out how to handle our python version at all on our own first. And choose to do it in master, but I could have done it in beta too :shrug:

**Comment by wsnipex** [comment]
for reference: the freedesktop sdk (and therefore kodi) currently uses https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/21.08/elements/components/python3.bst#L108

**Comment by wsnipex** [comment]
from the build log:

> -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.9.so (found suitable version "3.9.9", minimum required is "3.5")
-- Found Python: /usr/include/python3.9

**Comment by Erick555** [comment]
I think having bundled python in app could be challenging since then all runtime python modules would be lost. Basically you would have to maintain parallel python environment including things which depend on python. Maybe asking runtime to bump python to 3.9.13 would be acceptable solution?

**Comment by razzeee** [comment]
Only for beta. Stable expects python 3.8.

**Comment by Erick555** [comment]
I wonder how many of kodi users have python version it expects. Not many I guess.

**Comment by razzeee** [comment]
Fair, still, I think controlling the version makes sense, as that's what we do on other platforms too.

**Comment by cgcgcgcgcg** [comment]
I'm no expert but I too suggest using a freedesktop-sdk that uses python v3.8 to avoid -mostly badly written- addons or skins that use methods or calls that don't work in python v3.9 anymore.

**Comment by Erick555** [comment]
Older freedesktop-sdk has just 3 months of support left. This would also means downgrade of mesa and several other regressions. There is no free meal here.

**Comment by cgcgcgcgcg** [comment]
> Older freedesktop-sdk has just 3 months of support left. This would also means downgrade of mesa and several other regressions. There is no free meal here.

I hear you, I also agree with you, but that would mean addons, skins might not work.
When I opened an issue in -system Kodi not here- asking if Kodi could have a separate branch to support current Arch python version they probably thought I was an alien.

**Comment by razzeee** [comment]
Why would they? It also affects manjaro etc.
Still, very labor intensive fix to the problem.

**Comment by cgcgcgcgcg** [comment]
> Why would they? It also affects manjaro etc. Still, very labor intensive fix to the problem.

25th of September 2021:
https://github.com/xbmc/xbmc/issues/20172

**Comment by cgcgcgcgcg** [comment]
Sorry for the off topic question, is there a way I can use the Flatpak Kodi version that had the older freedesktop-sdk that used python v3.8?
I want to troubleshoot some addons and skins.

**Comment by razzeee** [comment]
> > Why would they? It also affects manjaro etc. Still, very labor intensive fix to the problem.
> 
> My last try on 25th of September 2021: [xbmc/xbmc#20172](https://github.com/xbmc/xbmc/issues/20172)

I don't think you asked for that there, still, it would be a very heavy handed approach.

This should help you running an old version:
https://askubuntu.com/a/1349197

**Comment by cgcgcgcgcg** [comment]
> > > Why would they? It also affects manjaro etc. Still, very labor intensive fix to the problem.
> > 
> > 
> > My last try on 25th of September 2021: [xbmc/xbmc#20172](https://github.com/xbmc/xbmc/issues/20172)
> 
> I don't think you asked for that there, still, it would be a very heavy handed approach.
> 
> This should help you running an old version: https://askubuntu.com/a/1349197

Thanks for the link.
Other than using Flatpak, I think using a separate xbmc branch with Kodi running eg on the same python version as Arch is the logical step.

**Comment by wsnipex** [comment]
what would that accomplish? We already know that this python version is causing issues.

**Comment by razzeee** [comment]
This is probably not needed with the new platform

**Pull request closed without merging**
