### PR TITLE
Add wayland binary

### LINKED ISSUE #13: wayland executable?
Is there a wayland executable? Or is wayland support disabled at the moment for the Flatpak version of Kodi? Regards, Achim

### PR DESCRIPTION
**Pull request by tilosp**
Resolves #13 

The kodi-x11 and kodi-wayland modules are largely identical.
@Marko10-000 and @comparascope would you be fine with switching to a yaml manifest?
Because then i could remove the duplicated code by using anchors.

### CODE REVIEW

**Comment by tilosp** [comment]
bot, build

**Comment by TingPing** [comment]
You'd need a wrapper script to find the correct binary to launch.

**Comment by tilosp** [comment]
> You'd need a wrapper script to find the correct binary to launch.

i guess that is why one is included :)
Take a look at `flatpak run --command=cat tv.kodi.Kodi /app/bin/kodi`

**Comment by wsnipex** [comment]
looks good to me. FYI: the kodi wrapper script already supports autodetecting wayland and gbm:
https://github.com/xbmc/xbmc/blob/master/tools/Linux/kodi.sh.in#L61-L79

**Comment by Marko10-000** [comment]
@wsnipex what about nvidia's eglstream. Does it work/does the script detect it?

**Comment by wsnipex** [comment]
> @wsnipex what about nvidia's eglstream. Does it work/does the script detect it?

not supported

**Comment by tilosp** [comment]
> @Marko10-000 and @comparascope would you be fine with switching to a yaml manifest?
> Because then i could remove the duplicated code by using anchors.

@Marko10-000 ?

**Comment by Marko10-000** [comment]
As long as flathub can build it, YAML is fine for me.

**Comment by tilosp** [comment]
It can build it, a lot of other apps are using it to. For example: https://github.com/flathub/io.github.GnomeMpv/blob/yaml/io.github.GnomeMpv.yml

I will convert it to YAML and if @comparascope doesn't like it i can still revert it.

**Comment by tilosp** [comment]
> Please do it on an separate pull request!!!

This would cause merge conflicts because they would both modify the same file. 
But i will wait until this is merged and open a new pr for the yml manifest.

**Comment by Marko10-000** [comment]
@tilosp that wouldn't be a problem. I will solve the merge conflicts (#19).

**Comment by Marko10-000** [comment]
..., I hate the mobile phone layout. Sorry, this shouldn't be closed.

**Comment by comparascope** [comment]
Closed with #20

**Pull request closed without merging**
