### PR TITLE
Update to Matrix 19.0b2

### PR DESCRIPTION
**Pull request by RyuzakiKK**
This updates the beta branch to the latest Matrix version 19.0b2.

### CODE REVIEW

**Comment by wsnipex** [comment]
please see https://github.com/flathub/tv.kodi.Kodi/issues/94
the kodi build steps need adjustment, we don't need to build 3 kodi binaries anymore
Could you handle this here?

**Comment by RyuzakiKK** [comment]
@wsnipex Sure, as soon as I have some time I'll try to do the required changes and test the result.

**Comment by RyuzakiKK** [comment]
I manually tested the X11 and Wayland windowing options and they both works as expected.

So far I haven't tested gbm but I guess it should work too.

**Comment by wsnipex** [comment]
thanks!

**Pull request merged**
