### PR TITLE
Update runtime

### PR DESCRIPTION
**Pull request by razzeee**

### CODE REVIEW

**Comment by razzeee** [comment]
Bot, build

**Comment by razzeee** [comment]
@flathubbot Bot, build

**Comment by razzeee** [comment]
bot, build

**Comment by Erick555** [comment]
https://gcc.gnu.org/gcc-14/porting_to.html

**Comment by razzeee** [comment]
Might make sense to just do this with the next version and hope, that kodi will be compatible to newer gcc versions by then.

**Pull request closed without merging**
