### PR TITLE
Pin adddons to commits instead of only using branches for versioning

### PR DESCRIPTION
**Pull request by razzeee**

### CODE REVIEW

**Comment by razzeee** [comment]
@wsnipex This is one way to get around the linter errors, I would also do this for master, if it's fine with you.
I know it's not ideal, as it needs a github token

**Comment by wsnipex** [comment]
this now requires code changes to update addons once again, not sure if that's desired.

**Comment by razzeee** [comment]
I think that's what the flathub maintainers want @barthalion

**Comment by razzeee** [comment]
The idea is that every build should be deterministic

**Comment by wsnipex** [comment]
should or must? Forcing projects into (potentially a lot of) extra work just to pass a linter is nonesense

**Comment by Erick555** [comment]
Currently it must. It's not possible to do anything here without pleasing the linter.

**Comment by razzeee** [comment]
We could ask for exceptions for each addon case, but that wouldn't be the popular option I guess

**Comment by wsnipex** [comment]
could we add a github action that does this periodically or on demand?

**Comment by razzeee** [comment]
> could we add a github action that does this periodically or on demand?

I think so, but I'm not sure if I want to spend that time now. Would like to fix beta and main for now and merge some of the other PRs.

**Comment by barthalion** [comment]
> should or must? Forcing projects into (potentially a lot of) extra work just to pass a linter is nonesense

The app wouldn't be accepted now without first pinning all commits. All the linter does is enforcing what would be pointed out during the initial review.

**Pull request merged**
