### PR TITLE
Update ghostscript to 9.26

### PR DESCRIPTION
**Pull request by Erick555**
Ghostscript 9.26 is yet another security related related release.
https://www.ghostscript.com/doc/9.26/News.htm

### CODE REVIEW

**Comment by tilosp** [comment]
bot, build

**Comment by Erick555** [comment]
If this is question for me then I don't know but recommend to drop ghostscript if it isn't really needed.

**Comment by wsnipex** [comment]
Kodi itself definitely doesn't need it. Maybe some addon needs it, but I'm not aware of that.
I'd try to remove it and see if the build fails

**Comment by comparascope** [comment]
The cmake patch from kodi disables all the pdf docs, so, this is not needed. ghostscript.json already was no longer used and can be removed.

**Pull request closed without merging**
