### PR TITLE
Split out debug symbols again

### PR DESCRIPTION
**Pull request by razzeee**
The new linter reports this as a warning and it's hopefully not broken anymore?

### CODE REVIEW

**Comment by wsnipex** [comment]
bot build

**Comment by Erick555** [comment]
Note that you still pass -g0 so there are no debug symbols at all. You may drop it as well if you want to debug this stuff.

**Comment by razzeee** [comment]
Not sure we actually want the debug info, but it should be split into a different flatpak, which we prevented with the old code. And the linter now warns us about that, as I mentioned.

**Comment by Erick555** [comment]
If you don't want to debug then the change is fine yet to be clear: you won't split anything because debuginfo doesn't exist before and after this change so the only effect of this change is to please the linter.

**Comment by razzeee** [comment]
Yeah, probably not worth the hassle

**Pull request closed without merging**
