### PR TITLE
Add PipeWire support

### LINKED ISSUE #240: Missing PipeWire permission
Kodi 21 Omega has added native PipeWire support, but the Flatpak package is missing permission. At the moment I'm setting "--filesystem=xdg-run/pipewire-0" to fix this.

### PR DESCRIPTION
**Pull request by neo1973**
The `-DENABLE_PIPEWIRE=ON` is optional as PipeWire is already build but I guess it doesn't hurt.

Fixes #240.

### CODE REVIEW

**Comment by razzeee** [comment]
bot, build

**Comment by razzeee** [comment]
Thanks!

**Comment by razzeee** [comment]
@neo1973 I will revert this for now

**Comment by Jusix** [comment]
@razzeee Why the hell was this reverted? Now my kodi setup is broken again.

**Comment by razzeee** [comment]
Cause it broke every ubuntu setup

**Comment by Jusix** [comment]
@razzeee That's not true. I'm using a Ubuntu setup and for me it's broken without this...

**Comment by razzeee** [comment]
Probably not 22.04. lts then

**Comment by Jusix** [comment]
Yes I have Ubuntu 24.04 with PipeWire only and no PulseAudio installed. But removing a valid permission from kodi as a workaround to handle bad sound setups seems like a really bad fix to me.

**Comment by razzeee** [comment]
It should still work fine, as it did work fine before this change. Maybe your settings specify pipewire somewhere, pipewire itself emulates pulse.

**Comment by Jusix** [comment]
No it's broken now and it was broken before this commit. My sound setup is clean as it should be. Only native pipewire and no pipewire-pulse installed. Why should I install another emulation layer like pulse when kodi has native pipewire support, that doesn't make sense.

**Comment by Erick555** [comment]
Kodi didn't handle very well mixed pulse/pipewire setup and the fix isn't  in stable release yet so revert was unfortunate but necessary decision. You may just set `--filesystem=xdg-run/pipewire-0` yourself and move on.

**Pull request merged**
