### PR TITLE
Issue #35 - Build on aarch64

### LINKED ISSUE #35: arm support (raspberry pi)
Is there a way to use this on arm?  If not?

Do you know if will be supported in near future.

### PR DESCRIPTION
**Pull request by hfiguiere**
Need to be tested first.

Close #35

### CODE REVIEW

**Comment by wsnipex** [comment]
- Arm should use OpenGLES instead of OpenGL
- I suspect we might need --device=all for GBM to work

**Comment by hfiguiere** [comment]
> * Arm should use OpenGLES instead of OpenGL

1. RPi has GL too
2. Doesn't the build detect it?

>     * I suspect we might need --device=all for GBM to work

That's already in the finish args.

**Comment by hfiguiere** [comment]
This starts up. It spam me with weather I want to enable the plugins, one by one, but I guess that's just an upstream UI issue.

I get error about vc4_drv_video and such and it seems that it's an ongoing problem.

However I also have errors about `nmblookup: command not found`

**Comment by razzeee** [comment]
> tarts up. It spam me with wether I want to enable the plugins, one by one, but I guess that's just an upstream UI issue.

Known unfortunately, I'm trying to get that looked into.

> However I also have errors about `nmblookup: command not found`

See: https://github.com/flathub/tv.kodi.Kodi/issues/71

Still weird, from a quick check, it seems like that should only be used on windows.

**Comment by Erick555** [comment]
`nmblookup` is part of samba and is currently being [deleted](https://github.com/flathub/tv.kodi.Kodi/blob/master/modules/samba/samba.json#L10) from kodi flatpak

**Comment by razzeee** [comment]
Closing, as we're now building aarch

**Pull request closed without merging**
