### PR TITLE
Bump Kodi to 18.0rc3-Leia

### PR DESCRIPTION
**Pull request by tilosp**

### CODE REVIEW

**Comment by tilosp** [comment]
@Marko10-000 @comparascope @wsnipex is it really necessary to have more than one reviewer for small PRs?
IMHO requiring more than one review for small PRs doesn't make sense if there are only three maintainers that are often not available.

**Comment by tilosp** [comment]
@wsnipex is there a reason why you haven't merged it?

**Comment by wsnipex** [comment]
sometimes authors prefer to press the button themselves :)

**Comment by tilosp** [comment]
@wsnipex i can't, but i am just a Contributor not a Collaborator

**Comment by wsnipex** [comment]
ah ok, didn't notice that, sorry for the delay.

**Pull request merged**
