### PR TITLE
Addon updater

### PR DESCRIPTION
**Pull request by wsnipex**
backport #140

### CODE REVIEW

**Comment by razzeee** [comment]
The build above seems to segfault for me

**Comment by razzeee** [comment]
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
--Type <RET> for more, q to quit, c to continue without paging--
Core was generated by `/app/lib/kodi/kodi.bin --devel'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fc48d36e8b7 in __memmove_avx_unaligned_erms ()
   from /usr/lib/x86_64-linux-gnu/libc.so.6
[Current thread is 1 (Thread 0x7fc44d4bb640 (LWP 25))]

```

**Comment by wsnipex** [comment]
> ```
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
> --Type <RET> for more, q to quit, c to continue without paging--
> Core was generated by `/app/lib/kodi/kodi.bin --devel'.
> Program terminated with signal SIGSEGV, Segmentation fault.
> #0  0x00007fc48d36e8b7 in __memmove_avx_unaligned_erms ()
>    from /usr/lib/x86_64-linux-gnu/libc.so.6
> [Current thread is 1 (Thread 0x7fc44d4bb640 (LWP 25))]
> ```

I can't reproduce, can you provide more info? 
- steps to repro
-  log / crashlog

**Review by razzeee — APPROVED** [review]

**Comment by razzeee** [comment]
Works fine for me on my other PC with X. Unfortunatly exits with wayland (nvidia), but the old master does too.

**Pull request merged**
