### PR TITLE
Build on aarch64 (2023 edition)

### PR DESCRIPTION
**Pull request by ssssam**
An updated version of https://github.com/flathub/tv.kodi.Kodi/pull/130.

Tested on a Raspberry Pi; the resulting binary successfully shows the main screen on the HDMI display. It doesn't seem to respond to keyboard events so I haven't yet tested it further.

### CODE REVIEW

**Comment by razzeee** [comment]
Hey, this looks nice, were you able to test this on actual hardware?

**Comment by fuzzard** [comment]
Tested on Debian Bookworm, aarch64.
Was able to add NFS share, playback video, open/use external sub file.

**Comment by ssssam** [comment]
> Hey, this looks nice, were you able to test this on actual hardware?

Thanks! yes I'm testing it on Raspberry Pi 4 on Fedora IoT.

The app loads and displays the UI, in standalone mode. If I run it inside Weston then it fails to start due to missing `simpledrm_dri.so`. There are a couple of issues in standalone mode too:

  * A warning about simpledrm_dri.so missing
  * Keyboard and mouse input don't work.
  
Here's the simpledrm warning:

```
[📦 tv.kodi.Kodi ~]$ kodi --debug
MESA-LOADER: failed to open simpledrm: /usr/lib/aarch64-linux-gnu/GL/default/lib/dri/simpledrm_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/GL/default/lib/dri, suffix _dri)
libva info: VA-API version 1.18.0
libva info: Trying to open /usr/lib/aarch64-linux-gnu/dri/simpledrm_drv_video.so
libva info: Trying to open /usr/lib/aarch64-linux-gnu/dri/intel-vaapi-driver/simpledrm_drv_video.so
libva info: Trying to open /usr/lib/aarch64-linux-gnu/GL/lib/dri/simpledrm_drv_video.so
libva info: va_openDriver() returns -1
```

Need to investigate what this means. There are various drivers in `/usr/lib/aarch64-linux-gnu/GL/default/lib/dri/` but indeed nothing named `simpledrm`.

Regarding keyboard and mouse input, the log shows this:

```
2023-08-20 21:32:01.928 T:8        info <general>: AddOnLog: peripheral.joystick: Enabling joystick interface "linux"
2023-08-20 21:32:01.931 T:8        info <general>: Register - new keyboard device registered on application->keyboard: Keyboard (0000:0
000)
2023-08-20 21:32:01.931 T:8        info <general>: Register - new mouse device registered on application->mouse: Mouse (0000:0000)
```

So something is happening with peripherals, but Kodi doesn't receive any input.

**Comment by fuzzard** [comment]
@razzeee has asked for some more info from my testing.

Im using Debian Bookworm aarch64 running in a VM on an Apple M1 Macbook Pro.
Sound is working fine in this.
I started up bomberman libretro core, and game audio was playing without an issue. UI sounds (Key press/movement) were also audible

**Comment by razzeee** [comment]
So what are your opinions? I think we would be fine, if we merge it like this?

**Comment by ssssam** [comment]
I think it's useful to merge now, if you're happy :)

**Pull request merged**
