### PR TITLE
Bump Kodi to 18.1-Leia

### PR DESCRIPTION
**Pull request by tilosp**

### CODE REVIEW

**Comment by tilosp** [comment]
bot, build

**Comment by tilosp** [comment]
bot, build

**Comment by tilosp** [comment]
bot, build

**Comment by wsnipex** [comment]
bot, build

**Comment by tilosp** [comment]
bot, build

**Comment by tilosp** [comment]
@wsnipex the latest build was successful.
It still shows the old failed builds under checks, but this a bug (https://github.com/flathub/buildbot/commit/d647c0e70d76c8e310bc290bcd0ece1b44c755e9)

**Comment by wsnipex** [comment]
thanks!

**Comment by tilosp** [comment]
@wsnipex it looks like like the build failed https://flathub.org/builds/#/builders/10/builds/10
can you log into buildbot and restart it. I can't because i have no commit access.

**Pull request merged**
