### PR TITLE
Update to 19.0-Matrix

### LINKED ISSUE #64: Binary addon (especially vfs.sftp)
Hi,

the readme build notes mentions the vfs.sftp addon (and the required testing) but I can't find it under *tv.kodi.Kodi/x86_64/.../files/lib/kodi/addons* dir.

Any pointers on how to build it for flatpaked Kodi?

### LINKED ISSUE #76: Matrix?
Hi, has anyone tried to port it to Matrix already?

### LINKED ISSUE #91: Update runtime to 20.08

### LINKED ISSUE #96: Please update to 18.9
Kodi is out of date. Please update to 18.9.

### PR DESCRIPTION
**Pull request by vilmasvensson**
This PR contains major changes to code structure to provide greater consistency and maintainability.
 - Update Kodi to 19.0-Matrix, closes #96 and closes #76
 - Update runtime to 20.08, fixes #91, obsoletes #92
 - Update all binary addons and include most, closes #64, obsoletes #86
 - Update dependencies
 - Update README.md with correct information

Note: Cleanup may be lacking for newly added modules.

### CODE REVIEW

**Comment by ukbeast** [comment]
Thank you for bring Kodi up to date on Flatpak,

Tried test build 40117 on Fresh install of Fedora 33.
Settings do not save, which is annoying as there are loads of popups regarding plugins, which happens on every launch.
Both on xorg and wayland.

**Comment by Erick555** [comment]
Can confirm above. While testing `beta` branch there is migration happening just after launch but in this PR it seems broken. There are so many changes here that I'm not sure if it's problem with upstream final release or with changes done here.

I recommend doing minimal update to 19.0 basing on beta branch which uses 20.08 already and see if it works then do rest of the changes later.

**Comment by vilmasvensson** [comment]
Thank you for testing, I will try updating on beta branch to see what the problem is.

**Comment by gipawu** [comment]
Greetings, the trouble about not saved settings is because _**kodi-sh-in.patch**_ is not applied anymore. I workarounded it using persist option:

`flatpak run --persist=.kodi tv.kodi.Kodi`

Furthermore, there are some nasty crashes on certain actions, such as playing some tv channels (I use vnsi vdr pvr backend)

`/usr/include/c++/10.2.0/bits/basic_string.h:1019: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.`

or installing some addons

```
terminate called after throwing an instance of 'fmt::v7::format_error'
  what():  format specifier requires numeric argument
```

**Comment by vilmasvensson** [comment]
Indeed, `kodi-sh-in.patch` cannot be applied anymore with the only thing changing from the beta branch being the update to 19.0-Matrix. I get the following output:

```
Applying patch kodi-sh-in.patch
patching file tools/Linux/kodi.sh.in
Hunk #1 FAILED at 27.
1 out of 1 hunk FAILED -- saving rejects to file tools/Linux/kodi.sh.in.rej
Error: module kodi: Child process exited with code 1
```
As for the fmt error, it is probably related to the bump in version. I will revert it to the last major version.

**Comment by Erick555** [comment]
> Indeed, kodi-sh-in.patch cannot be applied anymore with the only thing changing from the beta branch being the update to 19.0-Matrix.

You need to look at what changed at source file and update the patch accordingly.

**Comment by vilmasvensson** [comment]
712a84a fixed the issue with kodi.in.sh.patch

**Comment by ukbeast** [comment]
Works fine now.
However DVD playback doesn't work now, as it used to in 18.8.
I'm assuming sandboxing issue?
DVD icon shows in Kodi, but does not play.

**Comment by Erick555** [comment]
> However DVD playback doesn't work now, as it used to in 18.8.
> I'm assuming sandboxing issue?

If it worked before and sandbox didn't change then it's unlikely.

**Comment by ukbeast** [comment]
> > However DVD playback doesn't work now, as it used to in 18.8.
> > I'm assuming sandboxing issue?
> 
> If it worked before and sandbox didn't change then it's unlikely.

Issue is upstream :( https://github.com/xbmc/xbmc/pull/19226

**Comment by Erick555** [comment]
@wsnipex could you take a look if this PR is ok to merge for you? It would be nice to get flatpk kodi up to date.

**Comment by wsnipex** [comment]
Looks like ffmpeg was built without SSL support, this breaks lots of addons.
2021-03-03 16:48:32.113 T:127     DEBUG <general>: ffmpeg[0x555f6ddf4990X]: https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.

**Comment by Erick555** [comment]
it's this [change](https://github.com/flathub/tv.kodi.Kodi/pull/100/files#diff-9f13ba4a7f9086f7fa511163d8d8c988bba44225f3684b006cee6a1ba5a0b012L14). @vilmasvensson could you explain and possible revert that?

**Comment by vilmasvensson** [comment]
I accidentally removed GnuTLS when cleaning up options. I re-added it now.

**Comment by wsnipex** [comment]
thank you!

**Pull request merged**
