### PR TITLE
Add beta suffix to desktop entry

### PR DESCRIPTION
**Pull request by razzeee**

### CODE REVIEW

**Comment by razzeee** [comment]
image

however, it will still not allow stable and beta to show up in there. I guess we'll need to change the desktop file name for that too.

**Comment by razzeee** [comment]
Which also is a no-go, as the appid needs to match the .desktop file afaik.

**Comment by wsnipex** [comment]
we could rename the kodi binary if we really want this.

**Comment by razzeee** [comment]
I'm not convinced it's worth it.

and also @bilelmoussaoui mentioned, that it doesn't even work 
> most of the gnome apps uses a different app-id for the test builds which won't work in flathub

**Pull request merged**
