### PR TITLE
don't enable pvr addons automatically

### PR DESCRIPTION
**Pull request by wsnipex**
enabling pvr addons by default causes crashing with a clean user data dir.

also see https://forum.kodi.tv/showthread.php?tid=366614

### CODE REVIEW

**Comment by Erick555** [comment]
Would this result in restoring addons installation popups after update? If yes then maybe default action could to to disable those addons and user could enable them manually when needed.

**Comment by wsnipex** [comment]
yes, it will, at first start. Still better then crashing from a fresh install...
IIRC there is no possibility to add all addons as "disabled". @howie-f any ideas?

**Comment by howie-f** [comment]
@wsnipex i think LE have a similar situation with their DVB driver add-ons.
it is solved there be disabling "auto activate and configure at startup" https://github.com/LibreELEC/LibreELEC.tv/pull/5403
is that the appropiate approach for flatpack, too?

**Comment by wsnipex** [comment]
thanks, let's try this.
Am I correct in assuming that with this patch, we don't need to add stuff to addon manifest?

**Comment by howie-f** [comment]
> we don't need to add stuff to addon manifest?

correct, all pvr-addons in the manifest wouldn't get activated/configured on startup

**Comment by howie-f** [comment]
i've tested the latest build and it is working like i would expect with the patch. clean start, all pvr add-ons are disabled by default. then you can enable and configure the pvr you want. i think this is the proper way

**Pull request merged**
